### ISSUE TITLE
Hero - Content wrapper

### ISSUE THREAD

**Issue by millertchris** [prolific-digital/waxcom#4]
This impacts both style-2 and style-3 and we may have to deviate a bit from our pattern.

In the mocks — the content at the bottom of the section has an opaque background that can be a different color. This background is supposed to stretch from edge to edge.

Add another `.wrapper` inside of the `.content` div and position the .content absolute to the bottom left with a width of 100%.  Then — create a `:before` pseudo element on the `.content` div and add the following CSS.

```
content: '';
position: absolute;
bottom: 0;
left: 0;
width: 100%;
height: 100%;
background: rgb(0 0 0 / 37%);
```

That should get close enough — I'll leave it to you to make it even better. 😉

https://github.com/prolific-digital/waxcom/blob/b776af938e006f522b2ad663a08509a55fb17e98/src/html/blocks/hero.html#L20-L28😉

**Comment by samuelsycamore** [comment]
Thank you, this was driving me nuts!!

**Comment by samuelsycamore** [comment]
Resolved today
