### ISSUE TITLE
Body - Remove margin

### ISSUE THREAD

**Issue by millertchris** [prolific-digital/waxcom#5]
Remove margin from the body tag  — this should remove the pesky spacing around the entire site. May want to remove padding too while you're at it — just so that it's defined.

**Comment by samuelsycamore** [comment]
Sure thing - where's the best place in all the various SCSS files to make changes like this?

**Comment by millertchris** [comment]
The layout.scss file should do!

**Comment by samuelsycamore** [comment]
Thanks! Global margin and padding have been set to 0 in layout.scss
