### ISSUE TITLE
Block (Services) - General layout and styling

### ISSUE THREAD

**Issue by millertchris** [prolific-digital/waxcom#7]
Here are my notes:

- [x] The wrapper doesn't seem to be impacting the section.
- [x] Firm up the spacing between title and content.
- [x] Put a max-width on each service item.
- [x] Titles require thinner font-weight and respective colors.
- [x] Increase padding inside "See More".
- [x] Move "See More" onto one line.
- [x] Use font-awesome for the "See More" arrow.
- [x] Export Monsters as PNG from XD file

https://github.com/prolific-digital/waxcom/blob/b776af938e006f522b2ad663a08509a55fb17e98/src/html/blocks/services.html#L1-L51

**Comment by samuelsycamore** [comment]
Monsters are in, but I broke my brain trying to figure out why the wrapper isn't cooperating. We'll have to look at it together.

**Comment by millertchris** [comment]
Sounds like a plan, Stan!

**Comment by samuelsycamore** [comment]
Knocked all these out in the coding session today!
