### ISSUE TITLE
Wrapper - padding

### ISSUE THREAD

**Issue by samuelsycamore** [prolific-digital/waxcom#8]
In layout.scss the wrapper currently looks like:

```
.wrapper {
	max-width: var(--site-width);
	margin: auto;
	padding: 0 2rem;
}
```

That 2rem padding is driving me nuts all throughout the site! Would it be kosher to remove it?

**Comment by millertchris** [comment]
That's totally fine if you want to remove it — however — keep in mind that
when the edge of the browser hits the wrapper — there will be no padding,
and the text runs the risk of butting up on edge.

I've found it usually to add global padding to the wrapper to ensure
content never touches the edge — if you have a trick up your sleeve or want
to try something different — I'm all for it.

*Chris Miller*
*Founder*
Prolific Digital
502-376-1634
prolificdigital.com

**Comment by samuelsycamore** [comment]
I tried it and ended up breaking way more stuff than what it fixed. Oh well!
